name: berberim_yanimda
description: Berberim Yanımda - çift yüzlü berber randevu uygulaması
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.3.4
  flutter_riverpod: ^2.4.8
  go_router: ^13.1.0
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_local_notifications: ^16.2.0
  firebase_messaging: ^14.7.10
  url_launcher: ^6.2.5
  flutter_rating_bar: ^4.0.1
  dotted_border: ^2.0.0+3
  form_validator: ^2.1.1
  collection: ^1.18.0
  uuid: ^4.4.0
  http: ^1.2.0
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.1
  riverpod_test: ^1.0.6
